package com.project.domain.model

enum class Category {
    NOODLE_SOUPS,
    RICE_DISHES,
    SOUPS,
    HOTPOTS,
    APPETIZERS_AND_STREET_FOOD,
    VEGETARIAN_DISHES,
    DESSERTS_AND_SWEET_SNACKS,
    SEAFOOD_DISHES,
    GRILLED_DISHES,
    STEAMED_DISHES,
    STREET_SNACKS_AND_BEVERAGES
}